# Generated by Django 2.0.7 on 2018-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paddler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('generation', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
